"use client";

// import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import { inter } from "./fonts";
import "./globals.css";
import { supabase } from "@/supabase";
import Sidebar from "@/components/Sidebar";
import NavBar from "@/components/Navigation";
import Hero from "@/components/Hero";
import { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          <main className="container min-h-screen flex flex-col">
            <NavBar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
