"use client";

// import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import { inter } from "./fonts";
import "./globals.css";
import { supabase } from "@/supabase";
import Sidebar from "@/components/Sidebar";
import NavBar from "@/components/Navigation";
import Hero from "@/components/Hero";
import { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [categories, setCategories] = useState<any>();

  const getAllCategories = async () => {
    let { data: Categories, error }: any = await supabase
      .from("Categories")
      .select("*");
    if (error) {
      setCategories(undefined);
    }
    setCategories(Categories);
  };

  useEffect(() => {
    getAllCategories();
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className="container min-h-screen">
            <NavBar categories={categories} />
            <main>
              <Hero />
              <section className="flex gap-4">
                <Sidebar categories={categories} />
                <div className="flex-1">{children}</div>
              </section>
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
